### ISSUE TITLE
Library for ajax request

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/nmr-predictor#1]
@stropitek Should we use for ajax requests https://www.npmjs.com/package/superagent ?

Or what is the best so that it returns a promise ??? https://www.npmjs.com/package/superagent-promise ???

https://github.com/cheminfo-js/nmr-predictor/blob/master/src/predict1D.js

**Comment by targos** [comment]
fetch is the future

**Comment by targos** [comment]
https://github.com/github/fetch

**Comment by lpatiny** [comment]
Thanks @targos ! So we should use
`npm install whatwg-fetch` in this library I guess. I will also move my other library to this code (chemcalc-extended)

**Comment by lpatiny** [comment]
Well I could not let it work and I don't know what is wrong. Is this library expected to work on the server side in node as well as on the client side ?

I did in another project something like 
```
var fetch = require('whatwg-fetch').fetch;

function getPubchemStats(id) {
    return fetch('https://pubchem.cheminfo.org/mfStats/search?id='+id).then(
        result => result.text()
    );
}
```

Which yields to the error 
```
XMLHttpRequest is not defined 
       at node_modules/whatwg-fetch/fetch.js:419:21
```

**Comment by stropitek** [comment]
The library is meant to be a polyfill in the browser, not a node.js implementation of `fetch`, [see the readme of the repo](https://github.com/github/fetch#read-this-first))

**Comment by stropitek** [comment]
Other libraries are node.js implementations of `fetch`, for example: https://github.com/bitinn/node-fetch

**Comment by lpatiny** [comment]
And what is the easy way then to make the same code that works in the browser and in node ?
Which would be the goal of this library.

**Comment by stropitek** [comment]
https://github.com/matthew-andrews/isomorphic-fetch

This will add the polyfill from whatwg-fetch when building the library for the browser with browserify, and use `node-fetch` in node.js. I'm not sure though if this is the right approach. Maybe we don't want to include the polyfill in the build...
@targos thoughts?

**Comment by andcastillo** [comment]
I'm using node-fetch. I just committed the code.

**Comment by lpatiny** [comment]
And it works as well from the browser ?

**Comment by targos** [comment]
I would go for isomorphic-fetch

**Comment by targos** [comment]
superagent is still good if you have trouble with interoperability. The latest versions are Promise compatible

**Comment by andcastillo** [comment]
Finally what worked was  isomorphic-fetch + es6promise.  Thanks
