### ISSUE TITLE
Should we keep this as a separate project ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/nmr-predictor#2]
nmr-predictor is included in spectra-data but both depends of openchemlib-extended.

Does this mean we will load twice openchemlib-extended (1Mb) ? I think case I think it would be better to remove this project and put in in spectra-data.

Any comment @stropitek

**Comment by targos** [comment]
> Does this mean we will load twice openchemlib-extended (1Mb) ?

Only if they depend on a different version

>  I think it would be better to remove this project and put in in spectra-data.

I don't think so. It's not directly related

**Comment by stropitek** [comment]
I agree with @targos. We should keep nmr-predictor a separate library

**Comment by lpatiny** [comment]
Ok good.
