### ISSUE TITLE
Compatibility with the browser ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/nmr-predictor#4]
Is the library working correctly in the browser ?

Just wondering if we could get rid of script.epfl.ch for the prediction or what is missing to reach this goal.

Thanks !

**Comment by andcastillo** [comment]
2D predictor is working. @jobo322 was working on the 2D simulation. It is supposed to be working. We need to be able to export the 2D spectrum to a Jcamp. And then we need the J coupling constants. We have to migrate the code from java? The result was not bad, at least, with that code.

**Comment by lpatiny** [comment]
OK cool !
I think if spinus is working we can already directly make the prediction without going to script. this is already a big improvement !
And this could then work already for 1H and 13C
After when 2D jcamp export is working it can also work for 2D. Also nice improvement !

Finally indeed the last step is to make our own prediction for 1H and for this seems the best for now is to migrate the code from java. Just ask me if you see some problems there.
